### ISSUE TITLE
Formatting Issues - Cluck University 103

### ISSUE THREAD

**Issue by OwenIbarra** [RewstApp/docs.rewst.help#91]
> This looks a little broken now 

 _Originally posted by @OwenIbarra in [ca81537](https://github.com/RewstApp/docs.rewst.help/commit/ca81537797ea24ee3ae49c21bd4f5921ee0b98ab#r147493083)_

**Comment by NovaBran** [comment]
We've reformatted the entire section, but please let me know if there's any other issues! Thanks for adding this here!
